task:
  name: gcc8
  container:
    image: lasote/conangcc8
  build_script:
  - sudo apt-get update
  - sudo apt-get install --assume-yes libbz2-dev libpng-dev libfreetype6-dev libz-dev git
  - pwd
  - gcc-8 --version
  - cmake --version
  - conan --version
  - export CXX=`which g++-8`
  - export CC=`which gcc-8`
  - mkdir build
  - cd build
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan 
  - conan install .. --build missing
  - cmake ..
  - VERBOSE=1 cmake --build . -- -j2
  test_script:
  - pwd
  - cd build
  - ctest -j2

task:
  name: clang6.0
  container:
    image: lasote/conanclang60
  build_script:
  - sudo apt-get update
  - sudo apt-get install --assume-yes libbz2-dev libpng-dev libfreetype6-dev libz-dev git
  - pwd
  - ls /usr/bin/clang*
  - clang-6.0 --version
  - cmake --version
  - conan --version
  - export CXX=`which clang++-6.0`
  - export CC=`which clang-6.0`
  - mkdir build
  - cd build
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan 
  - conan install .. --build missing
  - cmake .. -D BOOL:LIBCPP=ON
  - VERBOSE=1 cmake --build . -- -j2
  test_script:
  - pwd
  - cd build
  - ctest -j2

task:
  name: VisualStudio2017
  windows_container:
    image: berzns/buildtools2017
  build_script:
    - dir
    - "@\"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe\" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command \"iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))\" && SET \"PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin\""
