image:
  - Visual Studio 2017
clone_folder: c:\projects\source
build_script:
- cmd: >-
    mkdir build

    cd build
    
    pip install --user conan

    conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan 

    conan install .. --build missing

    cmake c:\projects\source -G "Visual Studio 15"
    
    cmake --build . --config "Debug"

test_script:
- cmd: ctest -C Debug

