image:
  - Visual Studio 2017
clone_folder: c:\projects\source
build_script:
- cmd: >-
    mkdir build

    cd build
    
    pip install --user conan

    C:\Users\appveyor\AppData\Roaming\Python\Scripts\conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan 

    C:\Users\appveyor\AppData\Roaming\Python\Scripts\conan install .. --build missing

    cmake c:\projects\source -G "Visual Studio 15 2017 Win64"
    
    cmake --build . --config "Release"

test_script:
- cmd: ctest -C Release

