version: 2
jobs:
  build:
    docker:
      - image: lasote/conangcc8
    working_directory: ~/arm_thing
    steps:
      - checkout
      - run: pwd
      - run: gcc-8 --version
      - run: cmake --version
      - run: conan --version
      - run: export CXX=`which g++-8`
      - run: export CC=`which gcc-8`
      - run: mkdir build
      - run: sudo apt-get update
      - run: sudo apt-get install --assume-yes libbz2-dev libpng-dev libfreetype6-dev libz-dev
      - run: cd build; conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan 
      - run: cd build; conan install .. --build missing
      - run: cd build; cmake  $CMAKE_OPTS ..
      - run: cd build; VERBOSE=1 cmake --build . -- -j2
      - run: cd build; ctest -j2



